services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
    image: flask:tag
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
